### ISSUE TITLE
Package installation fails

### ISSUE THREAD

**Issue by tomasantunes** [royendgel/mjpeg-tools#5]
When I run the command "pip install mjpeg-tools" I get the following error:

Command "/usr/bin/python -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-aaFjzS/pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-7Yq8D_-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-aaFjzS/pillow/

**Comment by tomasantunes** [comment]
this is solved now. I had to install "libjpeg-dev" and "zlib1g-dev"

**Comment by royendgel** [comment]
Ok!!
